### ISSUE TITLE
Is there any plan about switching backends?

### ISSUE THREAD

**Issue by anqur** [owo-lang/MLPolyR#1]
LLVM? GRIN? Cmm? I mean a compiled and optimized type-checked program is desirable.

**Comment by LdBeth** [comment]
Ideally let's avoid working with multiple languages, so after doing some searches it seems MLRISC (despite the name suggests, it does generate IA-32 assembly) is the ideal choice although I heard it has stopped development. 
There are some previous efforts on porting MLpolyR to C--, but the current state of C-- I is much worse.
 I don't believe it is feasible to hand write LLVM IR emitter, and I doubt if there's any LLVM binding for SML/NJ still works.
GRIN is more about graph redu based.

Currently the Lambda code representation based interpreter is coming soon. It can execute a subset of the language
